### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by Soneji** [nodeca/url-unshort#10]
When running the example I get this deprecation message

```
(node:56484) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
Original url is: https://github.com/nodeca/url-unshort
```

Is it possible to fix this?

My versions:
```sh
node --version                                                        
v16.9.0

npm --version   
7.21.1

grep url-unshort package.json 
    "url-unshort": "^5.0.0",

```

**Comment by Soneji** [comment]
```sh
$ node --trace-deprecation "/dir/unshorten.js"
(node:57540) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at module.exports (/dir/node_modules/timed-out/index.js:9:17)
    at get (/dir/node_modules/url-unshort/node_modules/got/index.js:115:4)
    at Immediate.<anonymous> (/dir/node_modules/url-unshort/node_modules/got/index.js:124:3)
    at processImmediate (node:internal/timers:464:21)
Original url is: https://github.com/nodeca/url-unshort
```

**Comment by puzrin** [comment]
https://github.com/nodeca/url-unshort/commit/4be7314e9f918679cb9c1369e30ad13b404918e8
